# Generated by Django 5.0.6 on 2026-05-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_company_admin',
            field=models.BooleanField(default=False, verbose_name='É Administrador da Empresa?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name='Deve alterar a senha?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='perm_cert_design',
            field=models.BooleanField(default=True, verbose_name='Acesso a Configurar Certificado'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='perm_certificates_panel',
            field=models.BooleanField(default=True, verbose_name='Acesso a Central de Certificados'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='perm_company',
            field=models.BooleanField(default=True, verbose_name='Acesso a Minha Organização'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='perm_custom_forms',
            field=models.BooleanField(default=True, verbose_name='Acesso a Form Personalizado'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='perm_dashboard',
            field=models.BooleanField(default=True, verbose_name='Acesso ao Dashboard'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='perm_instructors',
            field=models.BooleanField(default=True, verbose_name='Acesso a Assinatura Certificado'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='perm_my_events',
            field=models.BooleanField(default=True, verbose_name='Acesso a Meus Eventos'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='perm_nps',
            field=models.BooleanField(default=True, verbose_name='Acesso a Form NPS'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='perm_participants',
            field=models.BooleanField(default=True, verbose_name='Acesso a Alunos/Participantes'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='perm_recurring_events',
            field=models.BooleanField(default=True, verbose_name='Acesso a Criar Evento Recorrente'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='perm_standard_events',
            field=models.BooleanField(default=True, verbose_name='Acesso a Criar Evento Padrão'),
        ),
    ]
