# Generated by Django 5.0.6 on 2026-02-18 23:42

import apps.certificates.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numeric_code', models.CharField(default=apps.certificates.models._generate_numeric_code, editable=False, max_length=20, unique=True, verbose_name='Código numérico')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/pdfs/', verbose_name='Arquivo PDF')),
                ('emitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Emitido em')),
                ('email_sent', models.BooleanField(default=False, verbose_name='E-mail enviado')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='E-mail enviado em')),
                ('whatsapp_sent', models.BooleanField(default=False, verbose_name='WhatsApp enviado')),
                ('whatsapp_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='WhatsApp enviado em')),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='registrations.registration', verbose_name='Inscrição')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['-emitted_at'],
            },
        ),
    ]
