# Generated by Django 5.0.6 on 2026-03-04 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
        ('core', '0004_alter_course_options_alter_instructor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core.company', verbose_name='Empresa'),
        ),
    ]
