# Generated by Django 5.0.6 on 2026-04-04 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_certificate_company'),
        ('core', '0014_alter_course_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Modelo Padrão, Modelo Imersão', max_length=100, verbose_name='Nome do Modelo')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='company/templates/', verbose_name='Modelo de Certificado (A4 Paisagem)')),
                ('title', models.CharField(blank=True, default='Certificado de Conclusão', max_length=80, null=True, verbose_name='Título do Certificado')),
                ('text_1', models.CharField(blank=True, default='Certificamos que', max_length=80, null=True, verbose_name='Texto 1')),
                ('text_2', models.CharField(blank=True, default='portador do CPF', max_length=80, null=True, verbose_name='Texto 2')),
                ('text_3', models.CharField(blank=True, default='concluiu com êxito o curso/treinamento', max_length=80, null=True, verbose_name='Texto 3')),
                ('text_4', models.CharField(blank=True, default='realizado na empresa fictícia na data', max_length=80, null=True, verbose_name='Texto 4')),
                ('text_5', models.CharField(blank=True, default='na Cidade de São Paulo. Estado de SP.', max_length=400, null=True, verbose_name='Texto 5')),
                ('text_6', models.CharField(blank=True, default='Com carga horária de:', max_length=80, null=True, verbose_name='Texto 6')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_templates', to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Modelo de Certificado',
                'verbose_name_plural': 'Modelos de Certificados',
            },
        ),
    ]
