# Generated by Django 5.0.6 on 2026-03-03 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-start_date'], 'verbose_name': 'Treinamento', 'verbose_name_plural': 'Treinamentos'},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'ordering': ['full_name'], 'verbose_name': 'Assinatura do Certificado', 'verbose_name_plural': 'Assinaturas do Certificado'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Término'),
        ),
        migrations.AddField(
            model_name='course',
            name='signature_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_sig1', to='core.instructor', verbose_name='Assinatura 1'),
        ),
        migrations.AddField(
            model_name='course',
            name='signature_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_sig2', to='core.instructor', verbose_name='Assinatura 2'),
        ),
        migrations.AddField(
            model_name='course',
            name='signature_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_sig3', to='core.instructor', verbose_name='Assinatura 3'),
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Função/Cargo'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Imagem da Assinatura'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='instructors/signatures/', verbose_name='Assinatura (Antiga)'),
        ),
    ]
