# Generated by Django 5.0.6 on 2026-03-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_course_institution_complement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
    ]
