# Generated by Django 5.0.6 on 2026-04-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_course_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(default='fbo.bonin@gmail.com', help_text='Atenção: Este e-mail receberá as respostas dos alunos.', max_length=254, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(blank=True, help_text='Atenção: A informação deste campo sairá impressa no certificado do aluno.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='Atenção: A informação deste campo sairá impressa no certificado do aluno.', null=True, upload_to='company_logos/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='Atenção: A informação deste campo sairá impressa no certificado do aluno.', max_length=200, verbose_name='Nome da empresa'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, help_text='Atenção: A informação deste campo sairá impressa no certificado do aluno.', verbose_name='Site'),
        ),
    ]
