# Generated by Django 5.0.6 on 2026-04-02 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_company_email_alter_company_cnpj_alter_company_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(blank=True, help_text='Atenção! Seu CNPJ sairá no certificado do seu aluno. Se for emitir como pessoa física, preencha com CPF.', max_length=20, null=True, verbose_name='CNPJ ou CPF'),
        ),
    ]
