# Generated by Django 5.0.6 on 2026-04-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_company_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='certificate_model',
            field=models.CharField(blank=True, choices=[('default', 'Modelo Padrão (Do sistema)'), ('custom', 'Modelo Personalizado')], max_length=20, null=True, verbose_name='Modelo de Certificado Ativo'),
        ),
        migrations.AddField(
            model_name='company',
            name='logo_position',
            field=models.CharField(choices=[('none', '1. Não adicionar Logo'), ('center', '2. Logo no centro e topo'), ('left', '3. Logo à esquerda e topo'), ('right', '4. Logo à direita e topo')], default='center', max_length=20, verbose_name='Posição da Logo'),
        ),
    ]
