# Generated by Django 5.0.6 on 2026-04-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_company_certificate_model_company_logo_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='custom_template',
            field=models.ImageField(blank=True, null=True, upload_to='company/templates/', verbose_name='Modelo de Certificado Personalizado (A4 Paisagem)'),
        ),
    ]
