# Generated by Django 5.0.6 on 2026-04-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_company_custom_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='custom_text_1',
            field=models.CharField(default='Certificamos que', max_length=80, verbose_name='Texto 1'),
        ),
        migrations.AddField(
            model_name='company',
            name='custom_text_2',
            field=models.CharField(default='portador do CPF', max_length=80, verbose_name='Texto 2'),
        ),
        migrations.AddField(
            model_name='company',
            name='custom_text_3',
            field=models.CharField(default='concluiu com êxito o curso/treinamento', max_length=80, verbose_name='Texto 3'),
        ),
        migrations.AddField(
            model_name='company',
            name='custom_text_4',
            field=models.CharField(default='realizado na empresa fictícia na data', max_length=80, verbose_name='Texto 4'),
        ),
        migrations.AddField(
            model_name='company',
            name='custom_text_5',
            field=models.CharField(default='na Cidade de São Paulo. Estado de SP.', max_length=100, verbose_name='Texto 5'),
        ),
        migrations.AddField(
            model_name='company',
            name='custom_text_6',
            field=models.CharField(default='Com carga horária de:', max_length=80, verbose_name='Texto 6'),
        ),
        migrations.AddField(
            model_name='company',
            name='custom_title',
            field=models.CharField(default='Certificado de Conclusão', max_length=80, verbose_name='Título do Certificado'),
        ),
    ]
