# Generated by Django 5.0.6 on 2026-04-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_company_custom_text_1_company_custom_text_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='custom_text_5',
            field=models.CharField(default='na Cidade de São Paulo. Estado de SP.', max_length=400, verbose_name='Texto 5'),
        ),
    ]
