# Generated by Django 5.0.6 on 2026-04-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_company_custom_text_5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='custom_text_1',
            field=models.CharField(blank=True, default='Certificamos que', max_length=80, null=True, verbose_name='Texto 1'),
        ),
        migrations.AlterField(
            model_name='company',
            name='custom_text_2',
            field=models.CharField(blank=True, default='portador do CPF', max_length=80, null=True, verbose_name='Texto 2'),
        ),
        migrations.AlterField(
            model_name='company',
            name='custom_text_3',
            field=models.CharField(blank=True, default='concluiu com êxito o curso/treinamento', max_length=80, null=True, verbose_name='Texto 3'),
        ),
        migrations.AlterField(
            model_name='company',
            name='custom_text_4',
            field=models.CharField(blank=True, default='realizado na empresa fictícia na data', max_length=80, null=True, verbose_name='Texto 4'),
        ),
        migrations.AlterField(
            model_name='company',
            name='custom_text_5',
            field=models.CharField(blank=True, default='na Cidade de São Paulo. Estado de SP.', max_length=400, null=True, verbose_name='Texto 5'),
        ),
        migrations.AlterField(
            model_name='company',
            name='custom_text_6',
            field=models.CharField(blank=True, default='Com carga horária de:', max_length=80, null=True, verbose_name='Texto 6'),
        ),
        migrations.AlterField(
            model_name='company',
            name='custom_title',
            field=models.CharField(blank=True, default='Certificado de Conclusão', max_length=80, null=True, verbose_name='Título do Certificado'),
        ),
    ]
