# Generated by Django 5.0.6 on 2026-04-03 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_company_custom_text_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(default='2024-01-01', verbose_name='Data de Início'),
            preserve_default=False,
        ),
    ]
