# Generated by Django 5.0.6 on 2026-04-04 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_certificatetemplate'),
        ('core', '0014_alter_course_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_template',
            field=models.ForeignKey(blank=True, help_text='Selecione o layout personalizado para os certificados deste treinamento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificates.certificatetemplate', verbose_name='Modelo de Certificado'),
        ),
    ]
