# Generated by Django 5.0.6 on 2026-04-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_course_certificate_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, max_length=350, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
