# Generated by Django 5.0.6 on 2026-04-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Deixe nulo para não expirar', null=True, verbose_name='Expira em'),
        ),
    ]
