# Generated by Django 5.0.6 on 2026-04-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_course_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='registration_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Término das Inscrições'),
        ),
        migrations.AddField(
            model_name='course',
            name='registration_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Início das Inscrições'),
        ),
    ]
