# Generated by Django 5.0.6 on 2026-04-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_course_registration_end_course_registration_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='expires_at',
        ),
        migrations.AddField(
            model_name='course',
            name='certificate_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Término da Solicitação'),
        ),
        migrations.AddField(
            model_name='course',
            name='certificate_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Início da Solicitação'),
        ),
    ]
