# Generated by Django 5.0.6 on 2026-04-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_course_expires_at_course_certificate_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='checkin_hash',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='Hash de Credenciamento'),
        ),
    ]
