# Generated by Django 5.0.6 on 2026-04-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_course_checkin_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='no_certificate',
            field=models.BooleanField(default=False, verbose_name='Este evento não terá certificado'),
        ),
    ]
