# Generated by Django 5.0.6 on 2026-04-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_course_no_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='certificate_end',
        ),
        migrations.RemoveField(
            model_name='course',
            name='certificate_start',
        ),
        migrations.AddField(
            model_name='course',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiração do Certificado'),
        ),
    ]
