# Generated by Django 5.0.6 on 2026-04-15 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_course_certificate_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPSForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Formulário')),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='Resposta Obrigatória?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nps_forms', to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Formulário NPS',
                'verbose_name_plural': 'Formulários NPS',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NPSQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Pergunta')),
                ('question_type', models.CharField(choices=[('score', 'Nota (0 a 10)'), ('text', 'Texto Livre')], default='score', max_length=10, verbose_name='Tipo de Pergunta')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('nps_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.npsform', verbose_name='Formulário')),
            ],
            options={
                'verbose_name': 'Pergunta NPS',
                'verbose_name_plural': 'Perguntas NPS',
                'ordering': ['order'],
            },
        ),
    ]
