# Generated by Django 5.0.6 on 2026-04-15 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_npsform_npsquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='nps_form',
            field=models.ForeignKey(blank=True, help_text='Selecione um formulário de feedback opcional para este evento.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.npsform', verbose_name='Formulário NPS'),
        ),
    ]
