# Generated by Django 5.0.6 on 2026-04-16 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_course_nps_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='nps_form',
            field=models.ForeignKey(blank=True, help_text='Selecione a pesquisa de satisfação para este evento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.npsform', verbose_name='Formulário NPS'),
        ),
    ]
