# Generated by Django 5.0.6 on 2026-04-17 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_course_nps_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Formulário')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_forms', to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Formulário Dinâmico',
                'verbose_name_plural': 'Formulários Dinâmicos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DynamicField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Rótulo do Campo')),
                ('field_type', models.CharField(choices=[('text', 'Texto Curto'), ('email', 'E-mail'), ('number', 'Número'), ('date', 'Data'), ('select', 'Seleção (Dropdown)'), ('checkbox', 'Caixa de Seleção')], max_length=20, verbose_name='Tipo do Campo')),
                ('is_required', models.BooleanField(default=False, verbose_name='Obrigatório?')),
                ('options', models.CharField(blank=True, help_text='Valores separados por vírgula para campos select', max_length=500, null=True, verbose_name='Opções')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='core.dynamicform', verbose_name='Formulário')),
            ],
            options={
                'verbose_name': 'Campo Dinâmico',
                'verbose_name_plural': 'Campos Dinâmicos',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='custom_cert_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cert_courses', to='core.dynamicform', verbose_name='Formulário de Solicitação Personalizado'),
        ),
        migrations.AddField(
            model_name='course',
            name='custom_reg_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reg_courses', to='core.dynamicform', verbose_name='Formulário de Inscrição Personalizado'),
        ),
    ]
