# Generated by Django 5.0.6 on 2026-04-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_dynamicform_dynamicfield_course_custom_cert_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicform',
            name='form_type',
            field=models.CharField(choices=[('REG', 'Inscrição (Pré-Evento)'), ('CERT', 'Solicitação de Certificado')], default='REG', max_length=10, verbose_name='Tipo de Formulário'),
        ),
    ]
