# Generated by Django 5.0.6 on 2026-04-19 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_certificatetemplate'),
        ('core', '0028_remove_course_expires_at_course_certificate_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nome do evento recorrente')),
                ('slug', models.SlugField(blank=True, max_length=350, null=True, unique=True, verbose_name='Slug')),
                ('hours', models.PositiveIntegerField(verbose_name='Carga horária total (horas)')),
                ('registration_start', models.DateTimeField(blank=True, null=True, verbose_name='Início das Inscrições')),
                ('registration_end', models.DateTimeField(blank=True, null=True, verbose_name='Término das Inscrições')),
                ('certificate_start', models.DateTimeField(blank=True, null=True, verbose_name='Início da Solicitação')),
                ('certificate_end', models.DateTimeField(blank=True, null=True, verbose_name='Término da Solicitação')),
                ('no_certificate', models.BooleanField(default=False, verbose_name='Este evento não terá certificado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certificate_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificates.certificatetemplate', verbose_name='Modelo de Certificado')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_events', to='core.company', verbose_name='Empresa')),
                ('custom_cert_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_cert_forms', to='core.dynamicform', verbose_name='Formulário de Solicitação Personalizado')),
                ('custom_reg_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_reg_forms', to='core.dynamicform', verbose_name='Formulário de Inscrição Personalizado')),
                ('nps_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.npsform', verbose_name='Formulário NPS')),
                ('signature_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_sig1', to='core.instructor', verbose_name='Assinatura 1')),
                ('signature_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_sig2', to='core.instructor', verbose_name='Assinatura 2')),
                ('signature_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_sig3', to='core.instructor', verbose_name='Assinatura 3')),
            ],
            options={
                'verbose_name': 'Evento Recorrente',
                'verbose_name_plural': 'Eventos Recorrentes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.TextField(verbose_name='Tema')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Conteúdo')),
                ('date', models.DateField(verbose_name='Data do Encontro')),
                ('start_time', models.TimeField(verbose_name='Hora de Início')),
                ('end_time', models.TimeField(verbose_name='Hora de Término')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('institution_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome da Instituição')),
                ('institution_street', models.CharField(blank=True, max_length=200, null=True, verbose_name='Rua/Avenida')),
                ('institution_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número')),
                ('institution_neighborhood', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('institution_complement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(max_length=2, verbose_name='Estado (UF)')),
                ('checkin_hash', models.UUIDField(blank=True, null=True, unique=True, verbose_name='Hash de Credenciamento')),
                ('recurring_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.recurringevent', verbose_name='Evento Recorrente')),
            ],
            options={
                'verbose_name': 'Encontro',
                'verbose_name_plural': 'Encontros',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
