# Generated by Django 5.0.6 on 2026-04-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_recurringevent_eventsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringevent',
            name='event_type',
            field=models.CharField(choices=[('CUSTOM', 'Personalizado (Apenas Lista de Presença, Sem Certificado)'), ('SCHEDULED', 'Programado (Com emissão de Certificado Geral)')], default='SCHEDULED', max_length=20, verbose_name='Tipo de Evento'),
        ),
    ]
