# Generated by Django 5.0.6 on 2026-04-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_recurringevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsession',
            name='hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Carga horária da sessão'),
        ),
        migrations.AddField(
            model_name='eventsession',
            name='session_passkey',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Chave de Acesso'),
        ),
    ]
