# Generated by Django 5.0.6 on 2026-04-20 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_eventsession_hours_eventsession_session_passkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='custom_reg_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reg_courses', to='core.dynamicform', verbose_name='Formulário de Inscrição'),
        ),
        migrations.AlterField(
            model_name='course',
            name='institution_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Local'),
        ),
        migrations.AlterField(
            model_name='eventsession',
            name='institution_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Local'),
        ),
        migrations.AlterField(
            model_name='recurringevent',
            name='custom_reg_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_reg_forms', to='core.dynamicform', verbose_name='Formulário de Inscrição'),
        ),
    ]
