# Generated by Django 5.0.6 on 2026-04-20 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_course_custom_reg_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsession',
            name='address_apt',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Apartamento/Casa'),
        ),
        migrations.AddField(
            model_name='eventsession',
            name='address_block',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bloco'),
        ),
        migrations.AddField(
            model_name='eventsession',
            name='address_floor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número/Letra do Andar'),
        ),
        migrations.AddField(
            model_name='eventsession',
            name='condominium_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Condomínio'),
        ),
        migrations.AddField(
            model_name='eventsession',
            name='country',
            field=models.CharField(blank=True, default='Brasil', max_length=100, null=True, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='eventsession',
            name='location_type',
            field=models.CharField(choices=[('condominio', '🏢 Condomínio (apartamento ou casa em condomínio)'), ('casa', '🏠 Casa (fora de condomínio)')], default='casa', max_length=20, verbose_name='Onde fica o endereço?'),
        ),
        migrations.AlterField(
            model_name='course',
            name='custom_cert_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cert_courses', to='core.dynamicform', verbose_name='Formulário de Solicitação de Certificado'),
        ),
        migrations.AlterField(
            model_name='recurringevent',
            name='custom_cert_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_cert_forms', to='core.dynamicform', verbose_name='Formulário de Solicitação de Certificado'),
        ),
    ]
