# Generated by Django 5.0.6 on 2026-04-20 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_eventsession_address_apt_eventsession_address_block_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsession',
            name='hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Carga horária do encontro'),
        ),
    ]
