# Generated by Django 5.0.6 on 2026-04-20 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_eventsession_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringevent',
            name='global_passkey',
            field=models.CharField(blank=True, help_text='Se definida, esta senha será exigida para todas as solicitações de certificado deste evento.', max_length=50, null=True, verbose_name='Chave de Acesso Global'),
        ),
    ]
