# Generated by Django 5.0.6 on 2026-04-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_recurringevent_global_passkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringevent',
            name='min_frequency',
            field=models.PositiveIntegerField(default=75, help_text='Porcentagem mínima de presença exigida para liberar o certificado.', verbose_name='Frequência Mínima Exigida (%)'),
        ),
        migrations.AlterField(
            model_name='recurringevent',
            name='hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Carga horária total (horas)'),
        ),
    ]
