# Generated by Django 5.0.6 on 2026-04-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_recurringevent_min_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringevent',
            name='min_frequency',
            field=models.PositiveIntegerField(default=75, help_text='Porcentagem mínima exigida para liberar o certificado.', verbose_name='Frequência Mínima Exigida (%)'),
        ),
    ]
