# Generated by Django 5.0.6 on 2026-04-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_course_global_passkey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamicform',
            options={'ordering': ['-created_at'], 'verbose_name': 'Formulário Personalizado', 'verbose_name_plural': 'Formulários Personalizados'},
        ),
        migrations.AddField(
            model_name='dynamicform',
            name='layout_type',
            field=models.CharField(choices=[('STRUCTURED', 'Formulário Estruturado (Automação de Certificado)'), ('FLEXIBLE', 'Formulário Flexível (Sem Certificado)')], default='STRUCTURED', max_length=20, verbose_name='Layout do Formulário'),
        ),
    ]
