# Generated by Django 5.0.6 on 2026-05-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_dynamicform_options_dynamicform_layout_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='default_certificate_color',
            field=models.CharField(choices=[('gray', 'Cinza'), ('blue', 'Azul Escuro'), ('red', 'Vermelho')], default='gray', max_length=20, verbose_name='Cor do Modelo Padrão'),
        ),
    ]
