# Generated by Django 5.0.6 on 2026-05-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_company_default_certificate_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='event_format',
            field=models.CharField(choices=[('online', 'Online'), ('presencial', 'Presencial'), ('hibrido', 'Híbrido')], default='presencial', max_length=20, verbose_name='Formato do Evento'),
        ),
        migrations.AddField(
            model_name='course',
            name='platform_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link do Evento'),
        ),
        migrations.AddField(
            model_name='course',
            name='platform_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Plataforma'),
        ),
        migrations.AlterField(
            model_name='course',
            name='hours',
            field=models.CharField(max_length=50, verbose_name='Carga horária'),
        ),
        migrations.AlterField(
            model_name='eventsession',
            name='hours',
            field=models.CharField(default='0', max_length=50, verbose_name='Carga horária do encontro'),
        ),
        migrations.AlterField(
            model_name='recurringevent',
            name='hours',
            field=models.CharField(default='0', max_length=50, verbose_name='Carga horária total'),
        ),
    ]
