# Generated by Django 5.0.6 on 2026-05-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_course_event_format_course_platform_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='address_apt',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sala/Espaço'),
        ),
        migrations.AddField(
            model_name='course',
            name='address_block',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bloco'),
        ),
        migrations.AddField(
            model_name='course',
            name='address_floor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Andar'),
        ),
        migrations.AddField(
            model_name='course',
            name='condominium_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Prédio Comercial'),
        ),
        migrations.AddField(
            model_name='course',
            name='location_type',
            field=models.CharField(choices=[('condominio', '🏢 Prédio Comercial (sala ou espaço em condomínio)'), ('casa', '🏠 Sala Comercial (sala ou espaço fora de condomínio)')], default='casa', max_length=20, verbose_name='Onde fica o local do evento?'),
        ),
    ]
