# Generated by Django 5.0.6 on 2026-05-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_course_address_apt_course_address_block_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsession',
            name='event_format',
            field=models.CharField(choices=[('online', 'Online'), ('presencial', 'Presencial'), ('hibrido', 'Híbrido')], default='presencial', max_length=20, verbose_name='Formato do Encontro'),
        ),
        migrations.AddField(
            model_name='eventsession',
            name='platform_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link do Evento'),
        ),
        migrations.AddField(
            model_name='eventsession',
            name='platform_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Plataforma'),
        ),
    ]
