# Generated by Django 5.0.6 on 2026-02-18 23:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('status', models.CharField(choices=[('pending', 'Aguardando envio'), ('sent', 'Certificado enviado')], default='pending', max_length=10, verbose_name='Status')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('birth_date', models.DateField(verbose_name='Data de nascimento')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('whatsapp', models.CharField(help_text='Somente números com DDD. Ex.: 11999999999', max_length=20, verbose_name='WhatsApp')),
                ('rg', models.CharField(max_length=20, verbose_name='RG')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('address', models.CharField(max_length=400, verbose_name='Endereço completo')),
                ('course_name', models.CharField(max_length=300, verbose_name='Nome do curso/treinamento')),
                ('course_city', models.CharField(max_length=100, verbose_name='Cidade onde foi realizado')),
                ('course_state', models.CharField(max_length=2, verbose_name='Estado (UF)')),
                ('course_workload', models.PositiveIntegerField(verbose_name='Carga horária (horas)')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='core.instructor', verbose_name='Instrutor')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'ordering': ['-created_at'],
            },
        ),
    ]
