# Generated by Django 5.0.6 on 2026-02-19 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='course_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de realização'),
        ),
    ]
