# Generated by Django 5.0.6 on 2026-02-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_registration_course_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='course_city',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='course_state',
        ),
        migrations.AddField(
            model_name='registration',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='course_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
