# Generated by Django 5.0.6 on 2026-03-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_remove_registration_course_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='custom_gender',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Qual?'),
        ),
        migrations.AddField(
            model_name='registration',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, null=True, verbose_name='Gênero'),
        ),
        migrations.AddField(
            model_name='registration',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profissão'),
        ),
    ]
