# Generated by Django 5.0.6 on 2026-03-04 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_course_options_alter_instructor_options_and_more'),
        ('registrations', '0004_registration_custom_gender_registration_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='core.course', verbose_name='Treinamento'),
        ),
    ]
