# Generated by Django 5.0.6 on 2026-03-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_registration_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='course_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Nome do curso/treinamento'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='course_workload',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Carga horária (horas)'),
        ),
    ]
