# Generated by Django 5.0.6 on 2026-03-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_alter_registration_course_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='institution_complement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='registration',
            name='institution_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome da Instituição'),
        ),
        migrations.AddField(
            model_name='registration',
            name='institution_neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='registration',
            name='institution_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='registration',
            name='institution_street',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Rua/Avenida'),
        ),
    ]
