# Generated by Django 5.0.6 on 2026-04-08 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0008_remove_registration_address_registration_cep_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['-created_at'], 'verbose_name': 'Solicitação de Certificado', 'verbose_name_plural': 'Solicitações de Certificado'},
        ),
    ]
