# Generated by Django 5.0.6 on 2026-04-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0009_alter_registration_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='attended',
            field=models.BooleanField(default=False, verbose_name='Presença Confirmada'),
        ),
    ]
