# Generated by Django 5.0.6 on 2026-04-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0010_registration_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='certificate_requested',
            field=models.BooleanField(default=False, verbose_name='Certificado Solicitado'),
        ),
    ]
