# Generated by Django 5.0.6 on 2026-04-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0011_registration_certificate_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='checkin_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora do Check-in'),
        ),
    ]
