# Generated by Django 5.0.6 on 2026-04-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0012_registration_checkin_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_requested',
            field=models.BooleanField(default=False, verbose_name='Certificado Solicitado'),
        ),
    ]
