# Generated by Django 5.0.6 on 2026-04-15 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_npsform_npsquestion'),
        ('registrations', '0013_registration_is_requested'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPSResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_score', models.IntegerField(blank=True, null=True, verbose_name='Nota')),
                ('answer_text', models.TextField(blank=True, null=True, verbose_name='Resposta em Texto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.npsquestion', verbose_name='Pergunta')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nps_responses', to='registrations.registration', verbose_name='Inscrição')),
            ],
            options={
                'verbose_name': 'Resposta NPS',
                'verbose_name_plural': 'Respostas NPS',
                'ordering': ['created_at'],
            },
        ),
    ]
