# Generated by Django 5.0.6 on 2026-04-17 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_dynamicform_dynamicfield_course_custom_cert_form_and_more'),
        ('registrations', '0014_npsresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True, verbose_name='Valor')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dynamicfield', verbose_name='Campo')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_responses', to='registrations.registration', verbose_name='Inscrição')),
            ],
            options={
                'verbose_name': 'Resposta Dinâmica',
                'verbose_name_plural': 'Respostas Dinâmicas',
            },
        ),
    ]
