# Generated by Django 5.0.6 on 2026-04-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0015_dynamicresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Somente números com DDD. Ex.: 11999999999', max_length=20, null=True, verbose_name='WhatsApp'),
        ),
    ]
