# Generated by Django 5.0.6 on 2026-04-19 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_recurringevent_eventsession'),
        ('registrations', '0016_alter_registration_birth_date_alter_registration_rg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='recurring_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='core.recurringevent', verbose_name='Evento Recorrente'),
        ),
        migrations.CreateModel(
            name='SessionPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False, verbose_name='Presente')),
                ('checkin_at', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora do Check-in')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_presences', to='registrations.registration', verbose_name='Inscrição')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='core.eventsession', verbose_name='Encontro')),
            ],
            options={
                'verbose_name': 'Presença no Encontro',
                'verbose_name_plural': 'Presenças nos Encontros',
                'unique_together': {('registration', 'session')},
            },
        ),
    ]
