# Generated by Django 5.0.6 on 2026-04-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0017_registration_recurring_event_sessionpresence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='institution_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Local'),
        ),
    ]
