# Generated by Django 5.0.6 on 2026-04-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0018_alter_registration_institution_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='address_apt',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Apartamento/Casa'),
        ),
        migrations.AddField(
            model_name='registration',
            name='address_block',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bloco'),
        ),
        migrations.AddField(
            model_name='registration',
            name='address_floor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número/Letra do Andar'),
        ),
        migrations.AddField(
            model_name='registration',
            name='condominium_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Condomínio'),
        ),
        migrations.AddField(
            model_name='registration',
            name='country',
            field=models.CharField(blank=True, default='Brasil', max_length=100, null=True, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='registration',
            name='location_type',
            field=models.CharField(choices=[('condominio', '🏢 Condomínio (apartamento ou casa em condomínio)'), ('casa', '🏠 Casa (fora de condomínio)')], default='casa', max_length=20, verbose_name='Onde fica o endereço?'),
        ),
    ]
