# Generated by Django 5.0.6 on 2026-04-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0019_registration_address_apt_registration_address_block_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Função/Profissão'),
        ),
    ]
