# Generated by Django 5.0.6 on 2026-05-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0021_alter_registration_cpf_alter_registration_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='course_workload',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Carga horária'),
        ),
    ]
